2021-05-26 11:56:49,389    DEBUG ---> Запуск client02.py   
2021-05-26 11:56:49,394    DEBUG ---> Создаём экземпляр Client   
2021-05-26 11:56:49,395    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1622019409.395653', 'alert': 'Please connect'}   
2021-05-26 11:56:56,685    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1622019416.684924', 'action': 'connect', 'chat': None}   
2021-05-26 11:57:05,494    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1622019425.493983', 'user': {'login': 'Ivan', 'pass': 'ppp'}}   
2021-05-26 11:57:05,578    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1622019425.577641', 'action': 'authorization', 'chat': None}   
2021-05-26 11:57:15,464    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1622019425.578711', 'user': {'login': 'Ivan', 'pass': 'ppp'}, 'msg': 'Здоров!', 'nChat': '3'}   
2021-05-26 11:57:15,478    ERROR ---> Ran out of input   
2021-05-26 11:57:47,240    DEBUG ---> Запуск client02.py   
2021-05-26 11:57:47,241    DEBUG ---> Создаём экземпляр Client   
2021-05-26 11:57:47,241    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1622019467.2418818', 'alert': 'Please connect'}   
2021-05-26 11:57:56,321    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1622019476.3214405', 'action': 'connect', 'chat': None}   
2021-05-26 11:58:01,078    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1622019481.0783103', 'user': {'login': '1', 'pass': '1'}}   
2021-05-26 11:58:01,174    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1622019481.174093', 'action': 'authorization', 'chat': None}   
2021-05-26 11:58:05,125    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1622019481.1751647', 'user': {'login': '1', 'pass': '1'}, 'msg': '45555', 'nChat': '2'}   
2021-05-26 11:58:05,221    ERROR ---> Ran out of input   
2021-05-26 12:00:47,349    DEBUG ---> Запуск client02.py   
2021-05-26 12:00:47,350    DEBUG ---> Создаём экземпляр Client   
2021-05-26 12:00:47,351    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1622019647.3509598', 'alert': 'Please connect'}   
2021-05-26 12:00:55,454    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1622019655.4538739', 'action': 'connect', 'chat': None}   
2021-05-26 12:00:56,903    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1622019656.903488', 'user': {'login': '5', 'pass': '5'}}   
2021-05-26 12:00:57,081    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1622019657.08094', 'action': 'authorization', 'chat': None}   
2021-05-26 12:01:02,070    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1622019657.082005', 'user': {'login': '5', 'pass': '5'}, 'msg': '123', 'nChat': '1'}   
2021-05-26 12:01:02,142    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'time': '1622019662.1425128', 'action': 'chat', 'chat': [{'user': '5', 'msg': '123'}]}   
2021-05-26 12:01:09,818    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1622019657.082005', 'user': {'login': '5', 'pass': '5'}, 'msg': '2333', 'nChat': '2'}   
2021-05-26 12:01:09,833    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'time': '1622019669.8327613', 'action': 'chat', 'chat': [{'user': '5', 'msg': '2333'}]}   
